# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-26 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(default='', verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Название', max_length=120, verbose_name='')),
                ('year', models.CharField(default='Год', max_length=20, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Вид', max_length=120, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('country', models.CharField(max_length=120, verbose_name='Страна')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 26, 23, 18, 24, 936281), verbose_name='Время Добавления')),
                ('updated', models.DateTimeField(default=datetime.datetime(2020, 3, 26, 23, 18, 24, 936281), verbose_name='Время Обновления')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wine_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='winecat.Label')),
                ('wine_sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='winecat.Sort')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_artical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winecat.Wine'),
        ),
    ]
