# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-20 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20200320_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 14, 14, 56, 66618), verbose_name='Время Добавления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 14, 14, 56, 66618), verbose_name='Время Обновления'),
        ),
    ]
